### PR TITLE
configs: Jason's suggestions for power model

### PR DESCRIPTION
**Pull request by powerjg**
Here's some suggestions for improvements on the power model.

Overall, it's going in the right direction. I have a lot of changes that are simple python style things, and a few other changes here.

I've put some comments in about what I would have commented on a PR. Feel free to ask any questions about why I changed things.

I also extended the `arm-hello.py` example with the power model for testing. One really cool thing that I found is since this is all in python iterating on the power model is *incredibly quick*! You don't have to recompile or anything. 

One issue that's going to arise is that getting the vector stats doesn't seem to work. I'll work with Bobby on this.

### CODE REVIEW

**Comment by poal023** [comment]
Thanks for the feedback, Jason. These all look good to me, but I have a couple of questions:

- Lines 22/23 in `alu_power_model.py`: I noticed that the in-order CPU refers to int ALU accesses as `numIntAluAccesses`, while O3 refers to them as `intAluAccesses`, is this small difference intentional? If not, is this something I should correct locally?
- Line 68 in `arm_hello.py`: In your comment to put the power model in an extended core class, for clarity: does this mean we should try to integrate the power model directly with the O3/Simple/etc core classes? Or simply that we apply the power model per core, then tie them all together with a CPU power model? 
- For all files: In gem5, do names not leading with an underscore (e.g `self.name`) refer to SimObj properties, and not for a class itself? 
- For all files: Is there a reason why we should immediately panic if we cannot find a stat instead of telling the user it DNE, and zeroing it out?

**Comment by powerjg** [comment]
> Thanks for the feedback, Jason. These all look good to me, but I have a couple of questions:
> 
> * Lines 22/23 in `alu_power_model.py`: I noticed that the in-order CPU refers to int ALU accesses as `numIntAluAccesses`, while O3 refers to them as `intAluAccesses`, is this small difference intentional? If not, is this something I should correct locally?

I *think* the stats might be named slightly differently. However, I don't remember. You should test this.

> * Line 68 in `arm_hello.py`: In your comment to put the power model in an extended core class, for clarity: does this mean we should try to integrate the power model directly with the O3/Simple/etc core classes? Or simply that we apply the power model per core, then tie them all together with a CPU power model?

At some point, after we have developed a working power model that is somewhat "complete" (I don't know how/when we will decide this), *then* we will extend the classes in `src/python/gem5/components` to have power models. This is the path toward upstreaming the code. Before we do that, though, we should like what we have.

> * For all files: In gem5, do names not leading with an underscore (e.g `self.name`) refer to SimObj properties, and not for a class itself?

See https://github.com/gem5/gem5/blob/stable/src/python/m5/SimObject.py#L819 and https://github.com/gem5/gem5/blob/stable/src/python/m5/SimObject.py#L859 (mostly the second one).

This code says that if the name starts with `_`, then just set it like a normal python attribute. Otherwise, if it's a port, connect it, if it's a param, set the parameter value, and otherwise, assume that it's a child SimObject.

To answer your question, names without a leading underscore *either* refer to a **`SimObject` parameter**, a **Port**, or a **child `SimObject**.


> * For all files: Is there a reason why we should immediately panic if we cannot find a stat instead of telling the user it DNE, and zeroing it out?

Yeah, definitely. Think of this from a users' perspective. What happens if they miss that warning and get an answer of 12W and then publish that in a paper? If a user specifies they want to use a statistic and it silently (or quietly) is ignored, this will cause unexpected problems. We should avoid presuming to know what the user wants.

**Comment by poal023** [comment]
> I think the stats might be named slightly differently. However, I don't remember. You should test this.

I ran the modified power model you gave me on `x86-hello.py`, using both `TimingCPU` and  `O3CPU`, and it does appear that on O3 there exists `intAluAccesses` on the root of the core (so `cores.core.intAluAccesses`). But, on Timing, it's under the execute stats per core. 

>At some point, after we have developed a working power model that is somewhat "complete" (I don't know how/when we will decide this), then we will extend the classes in src/python/gem5/components to have power models. This is the path toward upstreaming the code. Before we do that, though, we should like what we have.

Would a good starting point of "completion" be when we've validated the power model for a CPU (some base, possibly O3 based on some OoO CPU) with known activation energies, running some benchmarks? 

> See https://github.com/gem5/gem5/blob/stable/src/python/m5/SimObject.py#L819 and https://github.com/gem5/gem5/blob/stable/src/python/m5/SimObject.py#L859 (mostly the second one).
>
>This code says that if the name starts with _, then just set it like a normal python attribute. Otherwise, if it's a port, connect it, if it's a param, set the parameter value, and otherwise, assume that it's a child SimObject.
>
>To answer your question, names without a leading underscore either refer to a SimObject parameter, a Port, or a child `SimObject.`

>Yeah, definitely. Think of this from a users' perspective. What happens if they miss that warning and get an answer of 12W and then publish that in a paper? If a user specifies they want to use a statistic and it silently (or quietly) is ignored, this will cause unexpected problems. We should avoid presuming to know what the user wants.

Thanks for the clarity on both of these. I agree, it probably wouldn't be a good idea to allow non-existent stats to sneak through results.

**Comment by mattsinc** [comment]
Thanks @powerjg for the feedback, this is helpful.  A few thoughts:

- In the example @poal023 put together, he had a "list" of components and then a loop that went through and integrated them.  Your updates removed this loop in favor of listing out the parts with additions between them.  When there are relatively few pieces for a given power model, this seems ok, but what if there are many (e.g., > 10)?  In this case, it feels like the loop structure would be superior ...
- Your updated example also removed the 4 classes for SRAM Retention, Clock Gating, etc. for all but the overall CPU model.  Just curious why you did that?  It seems like, if support for these alternatives were ever added, then we'd end up needing to add 3 more classes for each component to model them.  Maybe I'm missing why removing this part is a good idea?
- Can you comment more on why accessing the stats multiple times may return different values?  Unless there is an m5op that affects the stats between the two calls, it seems like they should return the same thing ... maybe just the stat gets updated in the meantime by the program?

Ultimately though, my takeaway from this is, barring some small formatting and other issues, we're on the right track and @poal023 should continue forward with creating a full model say for MinorCPU -- then we should check that before continuing onto other CPUs or components.  Let me know if you disagree though :)

**Comment by powerjg** [comment]
> Thanks @powerjg for the feedback, this is helpful. A few thoughts:
> 
> * In the example @poal023 put together, he had a "list" of components and then a loop that went through and integrated them.  Your updates removed this loop in favor of listing out the parts with additions between them.  When there are relatively few pieces for a given power model, this seems ok, but what if there are many (e.g., > 10)?  In this case, it feels like the loop structure would be superior ...

It's all about readability. Remember, we should optimize for people reading the code, not for ourselves writing the code. We write the code once and read it 100s-1000s of times. IMO, code is not about communicating from human to the machine (though we do use it that way). It's more about communicating human to human. This is why, say, Python is better than assembly language or punch cards :D).

> * Your updated example also removed the 4 classes for SRAM Retention, Clock Gating, etc. for all but the overall CPU model.  Just curious why you did that?  It seems like, if support for these alternatives were ever added, then we'd end up needing to add 3 more classes for each component to model them.  Maybe I'm missing why removing this part is a good idea?

I go by the rule of "if the code isn't used, delete it." If we need more power models later, we can add them. There's always history in git (if you have good commits and good commit messages :)).

> * Can you comment more on why accessing the stats multiple times may return different values?  Unless there is an m5op that affects the stats between the two calls, it seems like they should return the same thing ... maybe just the stat gets updated in the meantime by the program?

Yeah. Say you're using the total instruction count. If you access it at time 1us and at time 1ms it will have different values. I'm a bit concerned about this in the longer term (i.e., after our initial implementation) because this essentially means we'll be finding the average power over longer and longer time periods. We probably *don't* want to reset **all** the stats every, say 1ms. So, we'll have to figure out how to solve this problem. 

> 
> Ultimately though, my takeaway from this is, barring some small formatting and other issues, we're on the right track and @poal023 should continue forward with creating a full model say for MinorCPU -- then we should check that before continuing onto other CPUs or components. Let me know if you disagree though :)

Yes, definitely!

**Pull request merged**
